# Generated by Django 4.1.6 on 2023-02-13 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_issuedbook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuedbook",
            name="book_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book",
                to="core.book",
            ),
        ),
        migrations.AlterField(
            model_name="issuedbook",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
