# Generated by Django 4.1.6 on 2023-02-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_issuedbook_book_id_alter_issuedbook_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuedbook",
            name="fine",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
